jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: poetry install --extras "testing"
      - run:
          name: Run tests
          command: make test

  deploy-docs:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "40:21:77:c0:92:84:7a:ee:ee:ae:aa:01:bd:d8:39:7a"
      - run:
          name: Install Python dependencies
          command: poetry install --extras "docs"
      - run:
          name: Build and deploy documentation
          command: poetry run mkdocs gh-deploy -m "Deployed {sha} with MkDocs version {version} [CI SKIP]"

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy-docs:
          requires:
            - test
          filters:
            branches:
              only: master
